const t={en:{models_title:"Models",download:"Download",download_quant8:"Download+INT8",chat_title:"Chat",quant_int8:"Quant INT8",quant_int4:"Quant INT4",generate:"Generate",del:"Delete"},zh:{models_title:"模型",download:"下载",download_quant8:"下载+INT8量化",chat_title:"对话",quant_int8:"INT8量化",quant_int4:"INT4量化",generate:"生成",del:"删除"}}
let lang="en"
const $=s=>document.querySelector(s)
function setLang(l){lang=l;document.querySelectorAll("[data-i18n]").forEach(e=>{const k=e.getAttribute("data-i18n");e.textContent=t[l][k]||k})}
async function sys(){const r=await fetch("/api/system/info");const j=await r.json();const acc=$("#accelerator");acc.innerHTML="";j.accelerators.forEach(a=>{const o=document.createElement("option");o.value=a.id;o.textContent=a.label;acc.appendChild(o)});const s=$("#sysinfo");s.textContent=`${j.os} ${j.os_version} · Python ${j.python} · Devices ${j.openvino_devices.join(", ")}`}
async function listModels(){const r=await fetch("/api/models/list");const j=await r.json();const c=$("#model_list");c.innerHTML="";const sel=$("#model_select");sel.innerHTML="";j.items.forEach(m=>{const d=document.createElement("div");d.className="item";const a=document.createElement("div");a.textContent=`${m.id} · ${(m.size_bytes/1024/1024).toFixed(2)} MB`;const b=document.createElement("div");const del=document.createElement("button");del.textContent=t[lang].del;del.onclick=async()=>{await fetch("/api/models/delete",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({model_id:m.id})});await listModels()};b.appendChild(del);d.appendChild(a);d.appendChild(b);c.appendChild(d);const opt=document.createElement("option");opt.value=m.id;opt.textContent=m.id;sel.appendChild(opt)})}
async function startDownload(){const id=$("#model_id").value.trim();if(!id)return;const include=$("#include").value.trim();const exclude=$("#exclude").value.trim();const revision=$("#revision").value.trim();const body={model_id:id};if(include)body.include=include.split(/\s+/);if(exclude)body.exclude=exclude.split(/\s+/);if(revision)body.revision=revision;const r=await fetch("/api/models/download",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();pollTask(j.task_id,async()=>{await listModels()})}
async function pollTask(taskId,onDone){const s=$("#download_status");s.innerHTML="";const wrap=document.createElement("div");wrap.className="progress";const bar=document.createElement("div");bar.className="bar";wrap.appendChild(bar);s.appendChild(wrap);const msg=document.createElement("div");s.appendChild(msg);let done=false;while(!done){const r=await fetch(`/api/tasks/${taskId}`);if(r.status!==200){msg.textContent="error";break}const j=await r.json();if(j.status==="running"&&(j.progress===undefined||j.progress<=1)){wrap.classList.add("ind")}else{wrap.classList.remove("ind");bar.style.width=(j.progress||0)+"%"}msg.textContent=j.message||"";if(j.status==="completed"){done=true;if(onDone)onDone()}if(j.status==="error"){done=true;msg.textContent=j.error||"error"}await new Promise(res=>setTimeout(res,1000))}}
async function downloadAndQuantizeInt8(){const id=$("#model_id").value.trim();if(!id)return;const include=$("#include").value.trim();const exclude=$("#exclude").value.trim();const revision=$("#revision").value.trim();const body={model_id:id};if(include)body.include=include.split(/\s+/);if(exclude)body.exclude=exclude.split(/\s+/);if(revision)body.revision=revision;const r=await fetch("/api/models/download",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!j.task_id)return;await new Promise(res=>pollTask(j.task_id,res));const modelLocalId=id.replace(/\//g,"__");const rq=await fetch("/api/models/quantize",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({model_id:modelLocalId,mode:"int8"})});const jq=await rq.json();if(jq.task_id){await new Promise(res=>pollTask(jq.task_id,res));await listModels();const sel=$("#model_select");const target=modelLocalId+"_quant_int8";for(const o of sel.options){if(o.value===target){sel.value=target;break}}}}
async function quantize(mode){const sel=$("#model_select");const id=sel.value;if(!id)return;const r=await fetch("/api/models/quantize",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({model_id:id,mode})});const j=await r.json();if(j.task_id)pollTask(j.task_id,async()=>{await listModels()})}
async function generate(){const id=$("#model_select").value;if(!id)return;const device=$("#accelerator").value||"CPU";const prompt=$("#prompt").value;if(!prompt)return;const config={max_new_tokens:parseInt($("#max_new").value,10),temperature:parseFloat($("#temperature").value),top_k:parseInt($("#top_k").value,10),top_p:parseFloat($("#top_p").value),repetition_penalty:parseFloat($("#rep_penalty").value)};const r=await fetch("/api/infer/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({model_id:id,device,prompt,config})});const j=await r.json();const out=$("#output");out.textContent=j.output||j.error||""}
function init(){setLang(lang);$("#lang").onchange=e=>setLang(e.target.value);$("#btn_download").onclick=startDownload;$("#btn_dl_quant_int8").onclick=downloadAndQuantizeInt8;$("#btn_quant_int8").onclick=()=>quantize("int8");$("#btn_quant_int4").onclick=()=>quantize("int4");$("#btn_generate").onclick=generate;sys().then(listModels)}
document.addEventListener("DOMContentLoaded",init)